[package]
name = "emugator-core"
version = "0.1.0"
authors = ["Liam Rosenfeld <me@liamrosenfeld.com>"]
edition = "2024"

[dependencies]
strum = { version = "0.27", features = ["derive"] }
bimap = "0.6"
ibig = "0.3.6"
peeking_take_while = "1.0.0"

[dev-dependencies]
rand = "0.9.0"
serde = "1.0.217"
