on: [push]

name: Rust Tests

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Node Dependencies
        working-directory: ./emugator_web
        run: npm install
      - name: Build Tailwind CSS
        working-directory: ./emugator_web
        run: npm run tailwind
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release --all-features
